/*
  # Seed initial data

  This migration populates the database with initial data for:
  1. Development and marketing tools
  2. Ticket packages
*/

-- Insert development tools
INSERT INTO tools (id, name, description, ticket_cost, url, is_affiliate, promo_code, icon_name, category, model, system_prompt, use_api)
VALUES
  ('builderall', 'BUILDERALL', 'CMS tout en un boosté à l''IA, permet de gérer une agence web, développer des sites de présentation, de commerce en ligne, des tunnels de vente, des Webinars, des formations, des blogs, des sondages, des prises de rendez-vous, gère les programmes d''affiliation multi-niveaux, très simple d''utilisation et très performant, il fonctionne en glisser/déposer, intègre WordPress et WooCommerce, permet d''utiliser ChatGPT comme aide en ligne, sans engagement sur la durée, outil conseillé dans la formation Réussite Online.', 0, 'https://1sh.co/6acedf33', true, 'NEWBIZ30', 'LayoutDashboard', 'development', NULL, NULL, false),
  ('systeme-io', 'SYSTEME IO', 'Outil de marketing tout en un pour réaliser vos tunnels de vente, votre e-mail marketing, des sites internet, vos webinars, vos formations en ligne, vos blogs, vos ventes de produits, pour faire du e-commerce, il est conseillé d''ajouter une solution WordPress ou WooCommerce fournie par LWS ou HOSTINGER.', 0, 'https://1sh.co/e67bdc65', true, NULL, 'PieChart', 'development', NULL, NULL, false),
  ('lws', 'LWS', 'Hébergeur français et fournisseur de noms de domaines, Nom de domaines, hébergement, serveur VPS, hébergement pour agences, AI développeur de sites natif ou Wordpress (Divi Site Builder), Banque d''images gratuites, garantie satisfait ou remboursé 30 jours, outil conseillé dans la formation Réussite Online.', 0, 'https://1sh.co/a496dad5', true, 'CF513', 'Server', 'development', NULL, NULL, false),
  ('hostinger', 'HOSTINGER', 'Hébergement infogéré pour WordPress et WooCommerce avec IA, hébergement pour agence web, VPS, développeur IA de sites internet, noms de domaine, e-mailing, support client h24 7/7.', 0, 'https://1sh.co/543bee10', true, NULL, 'Globe', 'development', NULL, NULL, false),
  ('bolt', 'BOLT', 'Plateforme de développement de site en mode conversationnel sans avoir besoin de toucher au code généré. Vérification en temps réel du site. Design agréable et professionnel.', 0, 'https://1sh.co/b8378c15', true, NULL, 'Zap', 'development', NULL, NULL, false),
  ('synthesys', 'SYNTHESYS', 'IA génératrice de vidéos avec avatar personnalisable, IA génératrice de voix personnalisable, IA génératrice d''images avec ou sans son, Traducteur de vidéos, doublage de vidéos, synthèse vocale, traduction audio par IA, générateur d''avatar.', 0, 'https://1sh.co/5db3888a', true, NULL, 'Video', 'development', NULL, NULL, false),
  ('invdeo', 'INVDEO', 'Générateur de vidéos et d''images adaptées aux différentes plateformes YouTube, TikTok, générateur de clips, création de films et courts métrages, gestion des sous-titres.', 0, 'https://1sh.co/1191ee2b', true, NULL, 'Film', 'development', NULL, NULL, false),
  ('elevenlabs', 'ELEVENLABS', 'Permet de dupliquer sa voix, ses intonations.', 0, 'https://1sh.co/a1397687', true, NULL, 'Mic', 'development', NULL, NULL, false),
  ('heygen', 'HEYGEN', 'Se cloner à partir d''une vidéo ou d''une photo.', 0, 'https://1sh.co/f4f3e46f', true, NULL, 'UserSquare2', 'development', NULL, NULL, false),
  ('akool', 'AKOOL', 'Change le visage sur une vidéo.', 0, 'https://1sh.co/aa2773aa', true, NULL, 'UserRound', 'development', NULL, NULL, false);

-- Insert marketing tools
INSERT INTO tools (id, name, description, ticket_cost, url, is_affiliate, promo_code, icon_name, category, model, system_prompt, use_api)
VALUES
  ('video-validator', 'Validation des vidéos', 'Validation des vidéos stockées dans un fichier .xlsx pour bâtir un fichier homogène avec visualisation de la vidéo et validation/suppression.', 0, NULL, false, NULL, 'CheckSquare', 'marketing', NULL, NULL, false),
  ('docx-concatenator', 'Concaténation de fichiers DOCX', 'Fusionnez deux fichiers DOCX en un seul document facilement.', 0, NULL, false, NULL, 'FileType', 'marketing', NULL, NULL, false),
  ('clone-ia-strategy', 'Clone IA pour votre stratégie', 'GPT qui réalise, en fonction des données et réponses fournies par l''opérateur, toute une stratégie de développement détaillée, étape par étape, permettant d''obtenir le résultat qu''il souhaite.', 5, NULL, false, NULL, 'Strategy', 'marketing', 'gpt-4o', 'Tu es un expert en stratégie d''entreprise. Ta mission est d''aider l''utilisateur à développer une stratégie détaillée, étape par étape, adaptée à son secteur d''activité et à ses objectifs. Pose des questions précises pour comprendre son projet, puis élabore un plan d''action concret avec des objectifs à court, moyen et long terme. Fournis des conseils spécifiques sur le positionnement, le marketing, les canaux de distribution et le développement commercial. Sois méthodique et pragmatique dans tes recommandations.', true),
  ('podcast-script-generator', 'Générateur de script de podcasts', 'GPT qui réalise, en fonction des données et réponses fournies par l''opérateur, des scripts optimisés pour des podcasts en veillant à soutenir l''attention des auditeurs et en utilisant des informations claires et faciles à comprendre.', 5, NULL, false, NULL, 'Mic2', 'marketing', 'gpt-4o', 'Tu es un expert en création de podcasts. Ta mission est de rédiger des scripts de podcast captivants et structurés. Ces scripts doivent être optimisés pour l''audio, avec un langage clair, engageant et conversationnel. Pose des questions sur le sujet du podcast, la durée souhaitée, le public cible et le ton général. Ensuite, crée un script complet qui inclut une introduction accrocheuse, des transitions fluides entre les segments, et une conclusion mémorable. Propose également des idées pour des effets sonores ou des musiques d''ambiance si approprié. Le script doit être facile à lire à voix haute et maintenir l''attention des auditeurs.', true),
  ('lead-magnet-generator', 'Générateur de Lead Magnet', 'GPT qui accompagne les utilisateurs dans la création de lead magnets percutants et attrayants pour capturer des emails efficacement. Il guide chaque étape du processus de création.', 5, NULL, false, NULL, 'Magnet', 'marketing', 'gpt-4o', 'Tu es un expert en marketing digital, spécialisé dans la création de lead magnets. Ta mission est d''aider l''utilisateur à concevoir un lead magnet attractif et pertinent pour son audience. Pose des questions sur son secteur d''activité, son public cible et ses objectifs. Ensuite, suggère plusieurs idées de lead magnets adaptés (guide PDF, checklist, mini-formation, webinaire, etc.). Une fois le type de lead magnet choisi, guide l''utilisateur dans la création du contenu, en fournissant une structure détaillée, des conseils sur le titre accrocheur, les points clés à inclure, et les meilleures pratiques pour maximiser les conversions. Fournis également des suggestions pour la promotion du lead magnet.', true),
  ('post-email-generator', 'Générateur de Posts et d''emails', 'GPT qui accompagne les utilisateurs dans la création automatisée de contenus marketing, notamment des emails de vente et des posts pour les réseaux sociaux.', 5, NULL, false, NULL, 'MailPlus', 'marketing', 'gpt-4o', 'Tu es un expert en marketing de contenu, spécialisé dans la rédaction d''emails et de posts pour les réseaux sociaux. Ta mission est d''aider l''utilisateur à créer des contenus engageants et convertissants. Pour les emails, tu dois créer des séquences efficaces (accueil, nurturing, vente, relance) avec des objets accrocheurs et des calls-to-action pertinents. Pour les posts sociaux, tu dois proposer des contenus adaptés à chaque plateforme (LinkedIn, Facebook, Instagram, etc.) en respectant les bonnes pratiques de chacune. Demande toujours des informations sur le public cible, l''objectif du contenu, le ton de voix souhaité et les éléments clés à inclure. Propose différents formats et des exemples concrets.', true),
  ('video-script-generator', 'Générateur de scripts de vidéos', 'GPT qui accompagne les utilisateurs dans la création de scripts captivants pour des vidéos YouTube, à la fois longues et courtes (Shorts).', 5, NULL, false, NULL, 'VideoIcon', 'marketing', 'gpt-4o', 'Tu es un expert en création de contenu vidéo pour YouTube. Ta mission est d''aider l''utilisateur à créer des scripts efficaces pour des vidéos longues ou des Shorts. Demande des informations sur le sujet, la durée cible, le public visé et le style souhaité. Pour les vidéos longues, crée un script structuré avec une introduction accrocheuse (hook), une présentation claire du contenu, des sections détaillées, et une conclusion avec call-to-action. Pour les Shorts, privilégie un contenu court, direct et captivant dès les premières secondes. Dans tous les cas, le script doit être conçu pour maximiser la rétention des spectateurs et l''engagement, avec un langage adapté à l''oral. Propose également des idées de titres accrocheurs, de miniatures et de mots-clés pertinents.', true),
  ('video-ideas-generator', 'Création de 50 idées de scripts vidéos', 'GPT qui accompagne les utilisateurs dans la fourniture de 50 idées de scripts captivants avec mots clés de recherche pour des vidéos YouTube.', 5, NULL, false, NULL, 'Lightbulb', 'marketing', 'gpt-4o', 'Tu es un expert en stratégie de contenu YouTube. Ta mission est de générer 50 idées de vidéos pertinentes pour la chaîne de l''utilisateur. Commence par lui demander son secteur d''activité, les thèmes principaux de sa chaîne, son public cible et les types de vidéos qu''il préfère créer. Ensuite, génère une liste de 50 idées de vidéos organisées par catégories thématiques. Pour chaque idée, propose : un titre accrocheur, une brève description du concept (1-2 phrases), et 3-5 mots-clés pertinents pour le référencement. Les idées doivent être variées, incluant du contenu éducatif, divertissant, des tutoriels, des analyses, des comparatifs, etc. Privilégie les sujets susceptibles de générer de l''engagement et des vues sur la plateforme, tout en restant pertinents pour le domaine d''expertise de l''utilisateur.', true),
  ('formation-generator', 'Générateur de formation', 'GPT qui accompagne les utilisateurs dans la création d''une formation en un ou plusieurs modules sur le sujet choisi.', 5, NULL, false, NULL, 'GraduationCap', 'marketing', 'gpt-4o', 'Tu es un expert en ingénierie pédagogique et en création de formations. Ta mission est d''aider l''utilisateur à concevoir une formation complète et structurée sur le sujet de son choix. Commence par lui poser des questions sur le sujet de la formation, le public cible, les objectifs pédagogiques, la durée souhaitée et le format (en ligne, présentiel, mixte). Ensuite, élabore un plan de formation détaillé avec : une introduction générale, des modules logiquement organisés, des leçons pour chaque module, des activités pratiques, des évaluations, et une conclusion. Pour chaque élément, propose du contenu concret et des méthodes pédagogiques adaptées. Suggère également des ressources complémentaires, des outils et des supports visuels pertinents. Ton approche doit garantir une progression pédagogique cohérente et favoriser l''engagement des apprenants.', true);

-- Insert ticket packages
INSERT INTO ticket_packages (id, name, amount, price)
VALUES
  ('basic', 'Pack Basique', 50, 19.99),
  ('standard', 'Pack Standard', 100, 34.99),
  ('premium', 'Pack Premium', 200, 59.99),
  ('ultimate', 'Pack Ultimate', 500, 99.99);